version: '3'

services:
  destination_database_service:
    image: mysql:8.0
    container_name: destination_database
    volumes:
      - ./destination/db/dbdata:/var/lib/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    ports:
        - "33061:3306"
  source_database_service:
    image: postgres
    container_name: source_database
    volumes:
      - ./source/db/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
        -   16015:5432
